### ISSUE TITLE
spark-engine21 randomly fails with NPE

### ISSUE THREAD

**Issue by oalam** [Hurence/logisland#283]
maybe surfire plugin issue

**Comment by oalam** [comment]
All tests should pass

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.66 sec <<< FAILURE! - in com.hurence.logisland.engine.ProgrammaticStreamProcessingIntegrationTest
validateIntegration(com.hurence.logisland.engine.ProgrammaticStreamProcessingIntegrationTest) Time elapsed: 22.415 sec <<< FAILURE!
java.lang.AssertionError: null
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.hurence.logisland.engine.ProgrammaticStreamProcessingIntegrationTest.validateIntegration(ProgrammaticStreamProcessingIntegrationTest.java:157)
