### ISSUE TITLE
NPE with QueryMatcher processor handling field with null value

### ISSUE THREAD

**Issue by jerome73** [Hurence/logisland#311]
# Expected behavior and actual behavior.
--------------------------------------------------------
Logisland Query Matcher processor should handle properly records with fields having no (null) values.
But when handling records containing fields with null values, Logisland hits the following NPE : 

2017-07-25 15:00:32 ERROR Executor:95 - Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IllegalArgumentException: value must not be null
    at shade.logisland.querymatcher.org.apache.lucene.document.Field.<init>(Field.java:246)
    at shade.logisland.querymatcher.uk.co.flax.luwak.InputDocument$Builder.addField(InputDocument.java:130)
    at com.hurence.logisland.processor.MatchQuery.process(MatchQuery.java:242)
  
# Steps to reproduce the problem.
----------------------------------------------
Configure logisland query matcher such as: 
 # Tag records based on query matching (presence of the hitType field with event as value)
        - processor: Tag_Records
          component: com.hurence.logisland.processor.MatchQuery
          type: processor
          documentation: a processor that tag records based on a query matching
          configuration:
            policy.onmiss: forward
            policy.onmatch: first
            output.record.type: match_query_event
            internal_traffic_hurence: hitType:event

Send a record containing fields with at least one null value; such as:

"referer" : null,
    "eventCategory" : "ButtonClick1ToHurence",
    "is_Link" : null,
    "remoteHost" : "192.168.1.19",
    "Alt" : "",
    "userAgentString" : "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36",
    "clickText" : null,
    "coverage_fr" : "L0",
    "path" : "C:\\Users\\Julien\\Documents\\Julien\\OpenAnalytics\\Fichiers\\Analytics\\fichiers_open_analytics_sprint2\\PIM\\logstash\\LIST-skus_multipleCoverage.csv",
    "viewportPixelWidth" : 1748,
    "companyID" : "",
    "host" : "DESKTOP-406DRM2",
    "localPath" : null,
    "partyId" : "0:j5ib9xgy:Uj1c0OEjcfBdxEhDML8mzldGdr56yjRT",
    "brandName" : "3M",
    "transactionCurrency" : "",
    "idERP1" : "0168-8100350",
    "is_newSession" : false,
    "transactionId" : null,
    "userRoles" : "",
    "productQuantity" : null,
    "screenPixelWidth" : 1855,
    "viewportPixelHeight" : 804,
    "brandId" : "1000",
    "pageViewId" : "0:CZVDyFKP94SCpoEokJP9vQ49tjw1d3GI",
    "Class" : "50-15-20-35",
    "transactionTotal" : 7.175E-43,
    "pointOfService" : "",
    "productPrice" : null,
    "clickURL" : "",
    "B2BUnit" : "",
    "fr" : "VHB TRANSFERT ADH ACRYL EP 0.25 12.7X5ML",
    "categoryName" : "",
    "eventAction" : "clickActionToHurence",
    "MYBRANDNAME" : "3M",
    "hitType" : "event",
    "pageType" : "",
    "Userid" : "N/A",
    "countryCode" : "fr",
    "@version" : "1",
    "newCustomerWebOnly" : 0,
    "coverage" : "L0",
    "categoryProductId" : "",
    "codeProduct" : "G1296007644",
    "GroupCode" : "",
    "categoryCode" : "",
    "sessionId" : "0:j5ib9xgy:e1M67Fw7SU8wzW~wo2~fazMJTa89W3EB",
    "message" : "G1296007644;PR_G1296007644;0168-8100350;;;;;;F9473PC.012ECS;1000;3M;;VHB TRANSFERT ADH ACRYL EP 0.25 12.7X5ML;;;;L0;L0;L0-IMG;L0;L0-IRA;;50-15-20-35-10\r",
    "eventLabel" : "fr",
    "record_type" : "pageView",
    "n" : null,
    "brandRef" : "F9473PC.012ECS",
    "categoryNiv2" : "50-15",
    "coverage_it" : "L0-IRA",
    "record_id" : "0:CZVDyFKP94SCpoEokJP9vQ49tjw1d3GIc",
    "categoryNiv1" : "50",
    "q" : null,
    "categoryNiv4" : "50-15-20-35",
    "coverage_en" : "L0",
    "@timestamp" : "2017-05-24T07:33:38.973Z",
    "categoryNiv3" : "50-15-20",
    "stockInfo" : null,
    "is_PunchOut" : "",
    "screenPixelHeight" : 1056,
    "h2kTimestamp" : 1501075060155,
    "location" : "file:///space/index.html",
    "newCustomerWebOrAgency" : 0,
    "record_time" : 1501075066244
  }

# Specifications like the version of the project, operating system, or hardware.
-------------------------------------------------------------------------------------------------------
Apply to logisland-0.10-1, all OSs, all HWs

**Comment by jerome73** [comment]
Fixed in PR #319
