### ISSUE TITLE
Cannot launch logisland (spark engine 1.6) in yarn cluster mode

### ISSUE THREAD

**Issue by jerome73** [Hurence/logisland#326]
# Expected behavior and actual behavior.
Logisland should be able to be launched in yarn cluster mode.
With hdp2.4, when launching logisland (spark engine 1.6) in yarn cluster mode, I got the following issue:

./bin/logisland.sh --conf ./conf/webanalytics-events-to-ES.yml --spark-home /usr/hdp/2.4.3.0-227/spark/
Warning: Ignoring non-spark config property: "spark.driver.extraJavaOptions=-Dlog4j.configuration=log4j.properties"
Warning: Ignoring non-spark config property: "spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties"
17/09/04 14:35:26 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/09/04 14:35:27 INFO TimelineClientImpl: Timeline service address: http://127.0.01:8188/ws/v1/timeline/
17/09/04 14:35:27 INFO RMProxy: Connecting to ResourceManager at 127.0.0.1:8050
17/09/04 14:35:27 WARN DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
17/09/04 14:35:27 INFO Client: Requesting a new application from cluster with 1 NodeManagers
17/09/04 14:35:27 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (14000 MB per container)
17/09/04 14:35:27 INFO Client: Will allocate AM container, with 2432 MB memory including 384 MB overhead
17/09/04 14:35:27 INFO Client: Setting up container launch context for our AM
17/09/04 14:35:27 INFO Client: Setting up the launch environment for our AM container
17/09/04 14:35:27 INFO Client: Using the spark assembly jar on HDFS because you are using HDP, defaultSparkAssembly:hdfs://hdfsdev/hdp/apps/2.4.3.0-227/spark/spark-hdp-assembly.jar
17/09/04 14:35:27 INFO Client: Preparing resources for our AM container
17/09/04 14:35:27 INFO Client: Using the spark assembly jar on HDFS because you are using HDP, defaultSparkAssembly:hdfs://hdfsdev/hdp/apps/2.4.3.0-227/spark/spark-hdp-assembly.jar
17/09/04 14:35:27 INFO Client: Source and destination file systems are the same. Not copying hdfs://hdfsdev/hdp/apps/2.4.3.0-227/spark/spark-hdp-assembly.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/logisland-spark_1_6-engine_2.10-0.10.1.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/logisland-spark_1_6-engine_2.10-0.10.1.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/zookeeper-3.4.6.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/zookeeper-3.4.6.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/zkclient-0.8.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/zkclient-0.8.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/yauaa-1.2.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/yauaa-1.2.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/xz-1.0.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/xz-1.0.jar
2:36 PM
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/xmlenc-0.52.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/xmlenc-0.52.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/unused-1.0.0.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/unused-1.0.0.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/stax-api-1.0-2.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/stax-api-1.0-2.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/spring-core-4.3.2.RELEASE.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/spring-core-4.3.2.RELEASE.jar
17/09/04 14:35:28 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/spark-streaming-kafka-assembly_2.10-1.6.2.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/spark-streaming-kafka-assembly_2.10-1.6.2.jar
17/09/04 14:35:29 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/snappy-java-1.0.5.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/snappy-java-1.0.5.jar
17/09/04 14:35:29 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/snakeyaml-1.12.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/snakeyaml-1.12.jar
17/09/04 14:35:29 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/slf4j-api-1.7.12.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/slf4j-api-1.7.12.jar
17/09/04 14:35:29 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/servlet-api-2.5.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/servlet-api-2.5.jar
17/09/04 14:35:29 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/scala-reflect-2.10.5.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/scala-reflect-2.10.5.jar
17/09/04 14:35:29 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/scala-logging-slf4j_2.10-2.1.2.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/scala-logging-slf4j_2.10-2.1.2.jar
17/09/04 14:35:30 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/scala-logging-api_2.10-2.1.2.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/scala-logging-api_2.10-2.1.2.jar
17/09/04 14:35:30 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/scala-library-2.10.5.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/scala-library-2.10.5.jar
17/09/04 14:35:30 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/scala-compiler-2.10.6.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/scala-compiler-2.10.6.jar
17/09/04 14:35:30 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/reflectasm-1.07-shaded.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/reflectasm-1.07-shaded.jar
17/09/04 14:35:30 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/quasiquotes_2.10-2.0.1.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/quasiquotes_2.10-2.0.1.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/protobuf-java-2.5.0.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/protobuf-java-2.5.0.jar
2:36 PM
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/paranamer-2.3.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/paranamer-2.3.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/opencsv-3.7.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/opencsv-3.7.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/objenesis-2.1.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/objenesis-2.1.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/netty-all-4.0.23.Final.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/netty-all-4.0.23.Final.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/netty-3.7.0.Final.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/netty-3.7.0.Final.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/mvel2-2.3.1.Final.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/mvel2-2.3.1.Final.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/minlog-1.2.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/minlog-1.2.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/metrics-core-2.2.0.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/metrics-core-2.2.0.jar
17/09/04 14:35:31 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/lz4-1.2.0.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/lz4-1.2.0.jar
17/09/04 14:35:32 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/logisland-utils-0.10.1.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/logisland-utils-0.10.1.jar
17/09/04 14:35:32 INFO Client: Uploading resource file:/opt/Logisland/logisland-0.10.1/lib/logisland-useragent-plugin-0.10.1.jar -> hdfs://hdfsdev/user/hurence/.sparkStaging/application_1496162735455_1121/logisland-useragent-plugin-0.10.1.jar
2:36 PM
17/09/04 14:35:32 WARN Client: Resource file:/opt/Logisland/logisland-0.10.1/lib/logisland-spark_1_6-engine_2.10-0.10.1.jar added multiple times to distributed cache.
17/09/04 14:35:32 INFO Client: Deleting staging directory .sparkStaging/application_1496162735455_1121
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed
    at scala.Predef$.require(Predef.scala:221)
    at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$8$$anonfun$apply$5.apply(Client.scala:501)
    at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$8$$anonfun$apply$5.apply(Client.scala:499)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$8.apply(Client.scala:499)
    at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$8.apply(Client.scala:497)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:497)
    at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:763)
    at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:143)
    at org.apache.spark.deploy.yarn.Client.run(Client.scala:1109)
    at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1169)
    at org.apache.spark.deploy.yarn.Client.main(Client.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

# Steps to reproduce the problem.
1- Install HDP2.4
2- Install Logisland (profile hdp2.4)
3- Launch a job in yarn cluster mode

# Specifications like the version of the project, operating system, or hardware.
Logisland 0.10.1 (profile HDP2.4)
OS: Linux Centos 7 for instance
HW: N/A

**Comment by jerome73** [comment]
The problem is located in logisland.sh where a sed instruction is not effective anymore due to the refactoring of logisland in spark engine 1.6 and 2.1.
Indeed now the jar /logisland-spark-engine*.jar does not exist anymore.
For hdp2.4, we have instead: logisland-spark_1_6-engine_2.10-0.10.1.jar

Proposed diff:

diff --git a/logisland-framework/logisland-resources/src/main/resources/bin/logisland.sh b/logisland-framework/logisland-resources/src/main/resources/bin/logisland.sh
index d093d78..db570b1 100755
--- a/logisland-framework/logisland-resources/src/main/resources/bin/logisland.sh
+++ b/logisland-framework/logisland-resources/src/main/resources/bin/logisland.sh
@@ -148,7 +148,7 @@ case $MODE in
     app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/logisland-elasticsearch-plugin-[^,]*.jar,#,#'`
     ;;
   yarn-cluster)
-    app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/logisland-spark-engine[^,]*.jar,#,#'`
+    app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/logisland-spark_[^,-]*-engine[^,]*.jar,#,#'`
     app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/guava-[^,]*.jar,#,#'`
     app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/elasticsearch-[^,]*.jar,#,#'`
     YARN_CLUSTER_OPTIONS="--master yarn --deploy-mode cluster --files ${CONF_FILE}#logisland-configuration.yml,file:${CONF_DIR}/log4j.properties --conf \"spark.driver.extraJavaOptions=-Dlog4j.configuration=log4j.properties\" --conf \"spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties\" --conf spark.ui.showConsoleProgress=false"
@@ -234,7 +234,7 @@ case $MODE in
     ;;
   yarn-client)
 
-    app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/logisland-spark-engine[^,]*.jar,#,#'`
+    app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/logisland-spark_[^,-]*-engine[^,]*.jar,#,#'`
     app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/guava-[^,]*.jar,#,#'`
     app_classpath=`echo ${app_classpath} | sed 's#,/[^,]*/elasticsearch-[^,]*.jar,#,#'`
