### ISSUE TITLE
SplitTextTest does not pass on some platforms (date parsing problem)

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#76]
On my Linux box, running the SplitTextTest within the IDE or with the command "mvn -DfailIfNoTests=false -Dtest=com.hurence.logisland.processor.SplitTextTest test" fails with this ending message:

#############################################
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Running com.hurence.logisland.processor.SplitTextTest
Tests run: 4, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.928 sec <<< FAILURE! - in com.hurence.logisland.processor.SplitTextTest
testApacheLog(com.hurence.logisland.processor.SplitTextTest)  Time elapsed: 0.296 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.hurence.logisland.record.StandardRecord.setTime(StandardRecord.java:114)
	at com.hurence.logisland.record.StandardRecord.<init>(StandardRecord.java:66)
	at com.hurence.logisland.util.runner.MockRecord.<init>(MockRecord.java:26)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.hurence.logisland.util.runner.StandardProcessorTestRunner.getOutputRecords(StandardProcessorTestRunner.java:241)
	at com.hurence.logisland.processor.SplitTextTest.testApacheLog(SplitTextTest.java:99)

testApacheLogWithoutRawContent(com.hurence.logisland.processor.SplitTextTest)  Time elapsed: 0.328 sec  <<< FAILURE!
java.lang.AssertionError: expected output error record count was 0 but is currently 200
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hurence.logisland.util.runner.StandardProcessorTestRunner.assertOutputErrorCount(StandardProcessorTestRunner.java:191)
	at com.hurence.logisland.processor.SplitTextTest.testApacheLogWithoutRawContent(SplitTextTest.java:120)

Results :

Failed tests: 
  SplitTextTest.testApacheLogWithoutRawContent:120 expected output error record count was 0 but is currently 200

#############################################

Some investigations show that the parsing of the date in the parsed apache log input record is failing with the default date configs of my platform and gives a ParseException:
java.text.ParseException: Unparseable date: "24/Jul/2016:08:45:28 +0200"
This leads to a RECORD_TIME left null in the output record and a later NPE.

**Comment by mathieu-rossignol** [comment]
Closing as fixed.
